[package]
name = "platform-mobile"
version = "0.1.0"
edition = "2021"

[dependencies]
ferment-interfaces = { path = "../ferment/ferment-interfaces" }
ferment-macro = { path = "../ferment/ferment-macro" }

platform-value = { path = "../platform/packages/rs-platform-value" }
data-contracts = { path = "../platform/packages/data-contracts" }
dpp = { path = "../platform/packages/rs-dpp" }
rs-sdk = { path = "../platform/packages/rs-sdk" }
rs-dapi-client = { path = "../platform/packages/rs-dapi-client" }
platform-version = { path = "../platform/packages/rs-platform-version" }

dotenvy = { version = "0.15.7", optional = true }
http = { version = "0.2.9" }
tokio = { version = "1.32.0", features = ["macros"] }
tracing-subscriber = { version = "0.3.16" }
tracing = { version = "0.1.37" }

#[build-dependencies]
#cbindgen = "0.26.0"
#ferment = { path = "../ferment/ferment" }
#toml = "0.8.8"

[lib]
name = "platform_mobile"
#crate-type = ["staticlib"]
